"""
AI Configuration API endpoints
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
from app.config import config_manager, settings
import os
from pathlib import Path

router = APIRouter()


class AIConfigResponse(BaseModel):
    provider: str
    model: str
    temperature: float
    max_tokens: int
    has_openai_key: bool
    has_anthropic_key: bool
    has_gemini_key: bool


class AIConfigUpdate(BaseModel):
    provider: Optional[str] = None
    model: Optional[str] = None
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    openai_api_key: Optional[str] = None
    anthropic_api_key: Optional[str] = None
    gemini_api_key: Optional[str] = None


@router.get("/ai-config", response_model=AIConfigResponse)
async def get_ai_config():
    """Get current AI configuration"""
    provider = config_manager.get("ai.provider", "gemini")
    model = config_manager.get("ai.model", "gemini-2.5-flash")
    temperature = config_manager.get("ai.temperature", 0.7)
    max_tokens = config_manager.get("ai.maxTokens", 2000)
    
    return {
        "provider": provider,
        "model": model,
        "temperature": temperature,
        "max_tokens": max_tokens,
        "has_openai_key": bool(settings.OPENAI_API_KEY),
        "has_anthropic_key": bool(settings.ANTHROPIC_API_KEY),
        "has_gemini_key": bool(settings.GEMINI_API_KEY),
    }


@router.put("/ai-config")
async def update_ai_config(config: AIConfigUpdate):
    """Update AI configuration"""
    try:
        # Update provider and model
        if config.provider is not None:
            config_manager.set("ai.provider", config.provider)
        if config.model is not None:
            config_manager.set("ai.model", config.model)
        if config.temperature is not None:
            config_manager.set("ai.temperature", config.temperature)
        if config.max_tokens is not None:
            config_manager.set("ai.maxTokens", config.max_tokens)
        
        # Update API keys in .env file
        env_file = Path(".env")
        env_lines = []
        api_keys_updated = {
            "OPENAI_API_KEY": config.openai_api_key,
            "ANTHROPIC_API_KEY": config.anthropic_api_key,
            "GEMINI_API_KEY": config.gemini_api_key,
        }
        
        # Read existing .env if it exists
        if env_file.exists():
            with open(env_file, "r") as f:
                for line in f:
                    line_stripped = line.strip()
                    # Check if this line is an API key we want to update
                    key_updated = False
                    for key_name, key_value in api_keys_updated.items():
                        if line_stripped.startswith(f"{key_name}="):
                            if key_value is not None:
                                env_lines.append(f"{key_name}={key_value}\n")
                            else:
                                # Keep existing value if not updating
                                env_lines.append(line)
                            key_updated = True
                            api_keys_updated[key_name] = None  # Mark as processed
                            break
                    
                    if not key_updated:
                        env_lines.append(line)
        
        # Add any new API keys that weren't in the file
        for key_name, key_value in api_keys_updated.items():
            if key_value is not None:
                env_lines.append(f"{key_name}={key_value}\n")
        
        # Write .env file
        with open(env_file, "w") as f:
            # Write header if file is new
            if not env_file.exists() or len(env_lines) == 0:
                f.write("# AI API Keys\n")
                f.write("# Generated by VeoFlow Studio\n\n")
            f.writelines(env_lines)
        
        # Update environment variables for current process
        # Note: This will only affect new requests, not already-running processes
        if config.openai_api_key is not None:
            os.environ["OPENAI_API_KEY"] = config.openai_api_key
            settings.OPENAI_API_KEY = config.openai_api_key
        if config.anthropic_api_key is not None:
            os.environ["ANTHROPIC_API_KEY"] = config.anthropic_api_key
            settings.ANTHROPIC_API_KEY = config.anthropic_api_key
        if config.gemini_api_key is not None:
            os.environ["GEMINI_API_KEY"] = config.gemini_api_key
            settings.GEMINI_API_KEY = config.gemini_api_key
        
        # Reload settings to pick up new API keys
        # Note: This won't affect already-running processes, but will work for new requests
        # For immediate effect, you'd need to restart the server
        
        return {
            "message": "AI configuration updated successfully",
            "provider": config.provider or config_manager.get("ai.provider", "gemini"),
            "model": config.model or config_manager.get("ai.model", "gemini-2.5-flash"),
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to update AI configuration: {str(e)}")

